#ifndef _TCPCUBE_EPOLL_HTTP_PARSER_H
#define _TCPCUBE_EPOLL_HTTP_PARSER_H

enum tcpcube_epoll_http_parser_state
{
    TCPCUBE_EPOLL_HTTP_PARSER_HTTP_METHOD_BEGIN,
    TCPCUBE_EPOLL_HTTP_PARSER_HTTP_METHOD,
    TCPCUBE_EPOLL_HTTP_PARSER_HTTP_METHOD_END,
    TCPCUBE_EPOLL_HTTP_PARSER_HTTP_URL_BEGIN,
    TCPCUBE_EPOLL_HTTP_PARSER_HTTP_URL,
    TCPCUBE_EPOLL_HTTP_PARSER_HTTP_URL_END,
    TCPCUBE_EPOLL_HTTP_PARSER_HTTP_VERSION_BEGIN,
    TCPCUBE_EPOLL_HTTP_PARSER_HTTP_VERSION,
    TCPCUBE_EPOLL_HTTP_PARSER_HTTP_VERSION_END,
    TCPCUBE_EPOLL_HTTP_PARSER_HTTP_HEADER_FIELD_BEGIN,
    TCPCUBE_EPOLL_HTTP_PARSER_HTTP_HEADER_FIELD,
    TCPCUBE_EPOLL_HTTP_PARSER_HTTP_HEADER_FIELD_END,
    TCPCUBE_EPOLL_HTTP_PARSER_HTTP_HEADER_VALUE_BEGIN,
    TCPCUBE_EPOLL_HTTP_PARSER_HTTP_HEADER_VALUE,
    TCPCUBE_EPOLL_HTTP_PARSER_HTTP_HEADER_VALUE_END,
    TCPCUBE_EPOLL_HTTP_PARSER_HTTP_HEADER_END
};

struct tcpcube_epoll_http_parser
{
    enum tcpcube_epoll_http_parser_state state;
    char* buffer;
    ssize_t buffer_offset;
    ssize_t buffer_size;
    char* token;
    ssize_t token_offset;
};

int tcpcube_epoll_http_parser_parse(struct tcpcube_epoll_http_parser* parser, ssize_t buffer_size);

#endif
